<?php if($this->getItems()->getSize()): ?>
<div class="block block-related">
    <p class="block-subtitle"><?php echo $this->__('Check items to add to the cart or') ?>&nbsp;<a href="#" onclick="selectAllRelated(this); return false;"><?php echo $this->__('select all') ?></a></p>
    <ol class="mini-products-list" id="block-related">
    <?php foreach($this->getItems() as $_item): ?>
        <li class="item">
            <?php if(!$_item->isComposite() && $_item->isSaleable()): ?>
                <?php if (!$_item->getRequiredOptions()): ?>
                    <input type="checkbox" class="checkbox related-checkbox" id="related-checkbox<?php echo $_item->getId() ?>" name="related_products[]" value="<?php echo $_item->getId() ?>" />
                <?php endif; ?>
            <?php endif; ?>
            <div class="product">
                <a href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_item->getName()) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_item, 'thumbnail')->resize(76) ?>" alt="<?php echo $this->htmlEscape($_item->getName()) ?>" /></a>
                <div class="product-details">
                    <p class="product-name"><a href="<?php echo $_item->getProductUrl() ?>"><?php echo $this->htmlEscape($_item->getName()) ?></a></p>
                    <?php echo $this->getPriceHtml($_item, true, '-related') ?>
                    <?php if ($this->helper('wishlist')->isAllow()) : ?>
                        <a href="<?php echo $this->getAddToWishlistUrl($_item) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a>
                    <?php endif; ?>
                </div>
            </div>
        </li>
    <?php endforeach ?>
    </ol>
    <script type="text/javascript">
    //<![CDATA[
        decorateList('block-related');
        $('.related-checkbox').click(addRelatedToProduct);
        var relatedProductsCheckFlag = false;
        function selectAllRelated(txt){
            if (relatedProductsCheckFlag == false) {
                $('.related-checkbox').attr('checked', 'checked');
                relatedProductsCheckFlag = true;
                txt.innerHTML="<?php echo $this->__('unselect all') ?>";
            }
            else {
                $('.related-checkbox').removeAttr('checked');
                relatedProductsCheckFlag = false;
                txt.innerHTML="<?php echo $this->__('select all') ?>";
            }
            addRelatedToProduct();
        }

        var symbol = '';
        var price = 0.00;
        var orgPrice = 0.00;
        var priceText = ($("[id^=product-price] .price").html());
        var re = /^([^\d]*)([\d.,]+)$/;

        if (matches = re.exec(priceText))
        {
            symbol = matches[1];// symbol
            price = parseFloat(matches[2].replace(',', ''));// price
        }

        orgPrice=price;
        if (orgPrice.toString().match(/^[\d]+$/)) {
            orgPrice = [orgPrice.toString(), '.00'].join('');
        }

        $('#relate-final-price').html(symbol + '' + formatNumber(orgPrice));

        function addRelatedToProduct(){
            var values = [];
            var total = 0.00;
            var subtotal = 0.00;
            var count = 0;
            $('.related-checkbox').each(function(){
                if($(this).attr('checked'))
                {
                    value = $(this).val();
                    val = value.split(',');
                    total += parseFloat(val[1]);
                    values.push(val[0]);
                    count += 1;
                }
            });

            subtotal = price * parseInt($('#qty').val()) + total;
            if (subtotal.toString().match(/^[\d]+$/)) {
                subtotal = [subtotal.toString(), '.00'].join('');
            }

            count += parseInt($('#qty').val());
            subtotal = Math.round(subtotal * 100) / 100;
            $('#item-amount').html(count.toString());
            $('#relate-final-price').html(symbol + '' + formatNumber(subtotal));
            if($('#related-products-field')){
                $('#related-products-field').val(values.join(','));
            }
        }

        $('#qty').live('change', function() {
            addRelatedToProduct();
        });
    //]]>
    </script>
</div>
<?php endif ?>
