
<?php if(count($this->getItemCollection()->getItems())): ?>
<div class="box-collateral box-up-sell">
    <h2><?php echo $this->__('You may also be interested in the following product(s)') ?></h2>
    <div class="products-grid upsell" id="upsell-product-table">
    <?php // $this->setColumnCount(5); // uncomment this line if you want to have another number of columns. also can be changed in layout ?>
    <?php $this->resetItemsIterator() ?>
    <?php for($_i=0;$_i<$this->getRowCount();$_i++): ?>

        <?php for($_j=0;$_j<$this->getColumnCount();$_j++): ?>
            <?php if($_link=$this->getIterableItem()): ?>
            <dl>
                <dt><a href="<?php echo $_link->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_link->getName()) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_link, 'small_image')->resize(150) ?>" alt="<?php echo $this->htmlEscape($_link->getName()) ?>" /></a></dt>
                <dd class="product-name"><a href="<?php echo $_link->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_link->getName()) ?>"><?php echo $this->htmlEscape($_link->getName()) ?></a></h3></dd>
                <dd><?php echo $this->getPriceHtml($_link, true, '-upsell') ?></dd>
                
            </dl>
            <?php endif; ?>
        <?php endfor; ?>

    <?php endfor; ?>
    </div>
    <script type="text/javascript">decorateTable('upsell-product-table')</script>
</div>
<?php endif ?>
