
<?php
 $shipmentinfo=$this->getShipment();
?>
<div>
  <?php foreach ($shipmentinfo as $shipments): ?>
  <?php foreach ($shipments as $shipment): ?>
  <?php $order = $shipment->getOrder();?>
  <div style="margin-top:20px;">
   <h1>Packingslip # <?php echo $shipment->getIncrementId()?></h1>
   <h1>Order # <?php echo $order->getRealOrderId()?></h1>
   <p class="order-date">Order Date: <?php echo Mage::helper('core')->formatDate($order->getCreatedAtStoreDate(), 'medium', false)?></p>
   <div class="col2-set">
      <div class="col-1">
         <h2>SOLD TO:</h2>
         <address><?php echo $order->getBillingAddress()->format('html')?></address>
	  </div>
	  <div class="col-2">
	     <h2>SHIP TO:</h2>
		 <address><?php echo $order->getShippingAddress()->format('html')?></address>
	  </div>
   </div>
   <div class="col2-set">
      <div class="col-1">
         <h2>Payment Method</h2>
          <?php  echo Mage::helper('payment')->getInfoBlock($order->getPayment())->setIsSecureMode(true)->toHtml();?>
      </div>
      <div class="col-2">
        <h2>Shipping Method:</h2>
        <p><?php echo $order->getShippingDescription()?>(Total Shipping Charges <?php echo $order->formatPriceTxt($order->getShippingAmount())?>)</p>
      </div>
	</div>
	<table class="data-table" id="my-orders-table">
		<col width="1" />
		<col/>
		<col width="1" />
		<col width="1" />
		<thead>
			<tr>
			    <th class="a-center">Qty</th>
				<th>Product Name</th>
				<th>SKU</th>	
			</tr>
		</thead>
		<?php $items=$shipment->getAllItems(); ?>
		<?php foreach ($items as $item): ?>
		<?php
	        $subtotal=$order->formatPriceTxt($item->getRowTotal() - $item->getDiscountAmount());
	    ?>
        <tbody>
			<tr class="border" id="order-item-row-7">
			    <td class="a-right">
			    <span class="nobr">
				    <?php echo ($item->getQty()*1)?>
				</span>
		        </td>
		        <td><h3 class="product-name"><?php echo $item->getName() ?></h3></td>
		        <td><?php echo $item->getSku() ?></td>
  	         </tr>
          </tbody>
		  <?php endforeach; ?>
      </table>
  </div>
 <?php endforeach; ?>
 <div style="margin-top:100px;"></div>
  <?php endforeach; ?>
</div>