<h1><?php echo $this->__('Send confirmation link') ?></h1>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="" method="post" id="form-validate">
    <div class="fieldset">
        <h2 class="legend"><?php echo $this->__('Retrieve your confirmation link here') ?></h2>
        <p><?php echo $this->__('Please enter your email below and we\'ll send you confirmation link for it.') ?></p>
        <ul class="form_list">
            <li class="fields">
                <label for="email_address" class="label-like"><em>*</em><?php echo $this->__('Email Address') ?></label>
                <div class="input-box">
                    <input type="text" name="email" id="email_address" title="<?php echo $this->__('Email Address') ?>" class="input-text required-entry validate-email" value="<?php echo $this->htmlEscape($this->getEmail()) ?>" />
                </div>
            </li>
        </ul>
		<li><button type="submit" title="<?php echo $this->__('Submit') ?>" class="button"><span><span><?php echo $this->__('Submit') ?></span></span></button></li>
    </div>
</form>
