<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<h2 class="font16"><?php echo $this->__('Retrieve your password here') ?></h2>
<form action="<?php echo $this->getUrl('*/*/forgotpasswordpost') ?>" method="post" id="form-validate">
	<div class="fieldset">

        <p style="text-align: center;">请输入您注册时所填的Email地址，我们会将您的新密码发送到您的邮箱内，请查收。</p>
		<ul class="form_list password_from">
			 <li class="fields">
				<label for="email_address" class="label-like"><?php echo $this->__('Email Address') ?><span class="required">*</span></label>
				<div class="input-box">
					<input type="text" name="email" alt="email" id="email_address" class="input-text" value="<?php echo $this->htmlEscape($this->getEmailValue()) ?>" validata="required:true" /><br/>
					<span class="prompt-msg" message=""></span> </div>
			</li>
			 <li class="fields">
				<button type="submit" title="<?php echo $this->__('Submit') ?>" class="button"><span><span><?php echo $this->__('Submit') ?></span></span></button>&nbsp;&nbsp;<a href="<?php echo $this->helper('customer')->getLoginUrl() ?>"><?php echo $this->__('Back to Login') ?></a>
			</li>
		</ul>
	</div>
</form>
<script type="text/javascript">
//<![CDATA[
    $(function() {
		 makingware.form.getInstance('#form-validate', {
	    	 error: {
	             required: '<?php echo Mage::helper('core')->__('Required Fields');?>',
	             email: '<?php echo Mage::helper('core')->__('Invalid %s address');?>'
	         }
		 }).submit(function(){
			 return $(this).data('this').isValidata();
		 });
	});
//]]>
</script> 
