<div class="account-login ">
 <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="login-form">
        <div class="col2-set clearfix">
		   <h2 class="font16"><?php echo $this->__('Login or Create an Account');?></h2>
            <div class="col-1 registered-users">
                <div class="content">
                    <ul class="form_list">
                        <li class="fields">
                            <label for="email" class="label-like"><?php echo $this->__('Account') ?>: </label>
                            <div class="input-box">
                                <input type="text" name="login[username]" id="email" class="input-text" title="<?php echo $this->__('Email Address');?>" validata="required:true" value="<?php if($this->getUsername()){echo $this->getUsername();}else{echo $this->getAllowLoginAttributeText();}?>" style="color:rgb(153, 153, 153);"/>
                                <span class="prompt-msg" message=""></span>
                            </div>
                        </li>
                        <li class="fields">
                            <label for="pass" class="label-like"><?php echo $this->__('Password') ?>: </label>
                            <div class="input-box">
                                <input type="password" name="login[password]" class="input-text" id="pass" title="<?php echo $this->__('Password') ?>" validata="required:true"/>
                                <span class="prompt-msg" message=""></span>
                            </div>
                        </li>
						<li class="fields"><button type="submit" class="button" title="<?php echo $this->__('Login') ?>" name="send" id="send2"><span><span><?php echo $this->__('Login') ?></span></span></button>  <a href="<?php echo $this->getForgotPasswordUrl() ?>"><?php echo $this->__('Forgot Your Password?') ?></a></li>
                    </ul>
                      <div class="buttons-set">
                </div>
                </div>
            </div>
             <div class="col-2 new-users">
                <div class="content clearfix">
                    <h2><?php echo $this->__('Why register as a member?');?></h2>
                   <p><?php echo $this->__('By creating an account with our store, you will be able to move through the checkout process faster, store multiple shipping addresses, view and track your orders in your account and more.') ?></p>
                    <button type="button" title="<?php echo $this->__('Create an Account') ?>" class="button" onclick="window.location='<?php echo $this->getCreateAccountUrl() ?>';"><span><span><?php echo $this->__('Create an Account') ?></span></span></button>
                </div>
            </div>
        </div>
    </form>
</div>

<?php if (Mage::helper('core')->isModuleEnabled('Makingware_ThirdLogin')):?>
	<?php echo $this->getHelper('thirdlogin/login')->toHtml();?>
<?php endif;?>

<script type="text/javascript">
//<![CDATA[
$(function() {
	var loginAccountText = "<?php echo $this->getAllowLoginAttributeText();?>";
	$("#login-form input[name='login\[username\]']").focus(function(){
		if ($(this).val() == loginAccountText){
			$(this).val('').css('color', '#333');
		}
	}).blur(function(){
		if ($(this).val() == '') {
			$(this).val(loginAccountText).css('color', '#999');
		}
	});
	
	makingware.form.getInstance('#login-form', {
    	error: {
            required: '<?php echo Mage::helper('core')->__('Required Fields');?>',
            minLength: '<?php echo Mage::helper('core')->__('At least %s characters');?>',
            email: '<?php echo Mage::helper('core')->__('Invalid %s address');?>'
        }
	}).submit(function(){
		return $(this).data('this').isValidata();
	});
});
//]]>
</script>
