


<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php echo $this->getChildHtml('form_before')?>
<form action="<?php echo $this->getAction() ?>" method="post" id="form-validate">
<div class="fieldset">
<h2 class="legend"><?php echo $this->__('Newsletter Subscription') ?></h2>
    <?php echo $this->getBlockHtml('formkey')?>
    <ul class="form_list">
        <li class="control">
		<div><input type="checkbox" name="is_subscribed" id="subscription" value="1" title="<?php echo $this->__('General Subscription') ?>"<?php if($this->getIsSubscribed()): ?> checked="checked"<?php endif; ?> class="checkbox" /><label for="subscription"><?php echo $this->__('General Subscription') ?></label></div></li>
		<li><button type="submit" title="<?php echo $this->__('Save') ?>" class="button"><span><span><?php echo $this->__('Save') ?></span></span></button></li>
    </ul>
</div>
</form>