<div class="indexcont">
<div class="ibox prolist bfL">
  <h3>当季热卖
    <ol class="num">
      <li class="numcur">家居装修</li>
      <li>消费电子</li>
      <li>服装饰品</li>
      <li>鲜花蛋糕</li>
    </ol>
  </h3>
  <div class="showbox">
  <ul class="ullist">
    <li>	<?php echo $this->getChildHtml("product_homepage") ?>   
    </li>
    <li><?php echo $this->getChildHtml("product_homepage") ?> </li>
    <li><img src="http://img.ffffound.com/static-data/assets/6/68e9a7a8476e26a1022fa5e39ccdda669a5d4f08_m.jpg" alt="demo" title="demo" /></li>
    <li><img src="http://img.ffffound.com/static-data/assets/6/68e9a7a8476e26a1022fa5e39ccdda669a5d4f08_m.jpg" alt="demo" title="demo" /></li>
  </ul>
</div>
<a class="pre">&laquo;向左滚动</a><a class="next">向右滚动&raquo;</a>
</div>
<?php echo $this->getChildHtml("index_left_box") ?> 
</span>