
<?php $_item = $this->getItem() ?>
<tr class="border" id="order-item-row-<?php echo $_item->getId() ?>">
    <td><h3 class="product-name"><?php echo $this->htmlEscape($_item->getName()) ?></h3>
        <?php if($_options = $this->getItemOptions()): ?>
        <dl class="item-options">
        <?php foreach ($_options as $_option) : ?>
            <dt><?php echo $this->htmlEscape($_option['label']) ?></dt>
            <?php if (!$this->getPrintStatus()): ?>
                <?php $_formatedOptionValue = $this->getFormatedOptionValue($_option) ?>
                <dd<?php if (isset($_formatedOptionValue['full_view'])): ?> class="truncated"<?php endif; ?>>
                    <?php echo $_formatedOptionValue['value'] ?>
                    <?php if (isset($_formatedOptionValue['full_view'])): ?>
                    <div class="truncated_full_value">
                        <dl class="item-options">
                            <dt><?php echo $this->htmlEscape($_option['label']) ?></dt>
                            <dd><?php echo $_formatedOptionValue['full_view'] ?></dd>
                        </dl>
                    </div>
                    <?php endif; ?>
                </dd>
            <?php else: ?>
                <dd><?php echo $this->htmlEscape( (isset($_option['print_value']) ? $_option['print_value'] : $_option['value']) ) ?></dd>
            <?php endif; ?>
        <?php endforeach; ?>
        </dl>
        <?php endif; ?>

        <!-- downloadable -->
        <?php if ($links = $this->getLinks()): ?>
            <dl class="item-options">
                <dt><?php echo $this->getLinksTitle() ?></dt>
                <?php foreach ($links->getPurchasedItems() as $link): ?>
                    <dd>
                    	<?php if ($link->getStatus() == Mage_Downloadable_Model_Link_Purchased_Item::LINK_STATUS_AVAILABLE):?>
                    	<a href="<?php echo $this->getUrl('downloadable/download/link', array('id' => $link->getLinkHash(), '_secure' => true));?>" 
                    		title="<?php echo Mage::helper('downloadable')->__('Start Download')?>" 
                    		<?php echo Mage::getStoreConfigFlag(Mage_Downloadable_Model_Link::XML_PATH_TARGET_NEW_WINDOW) ? 'onclick="this.target=\'_blank\'"' : ''; ?>>
                    		<?php echo $link->getLinkTitle();?>
                    	</a>
                    	<?php else:?>
                    		<?php echo $link->getLinkTitle();?>
                    	<?php endif;?>
                    </dd>
                <?php endforeach; ?>
            </dl>
        <?php endif; ?>
        <!-- EOF downloadable -->

        <?php echo $this->htmlEscape($_item->getDescription()) ?>
        <?php if($this->helper('giftmessage/message')->getIsMessagesAvailable('order_item', $_item) && $_item->getGiftMessageId()): ?>
            <br /><a href="#" id="order-item-gift-message-link-<?php echo $_item->getId() ?>" class="giftmessage-preview-link expand" onclick="return giftMessageToogle('<?php echo $_item->getId() ?>')"><?php echo $this->__('Gift Message') ?></a>
        <?php endif; ?>
    </td>
    <td><?php echo $this->htmlEscape(Mage::helper('core/string')->splitInjection($this->getSku())) ?></td>
    <td>
    </td>
    <td>
        <span class="nobr">
                <?php if ($this->getItem()->getQtyOrdered() > 0): ?>
            <?php echo $this->__('Ordered'); ?>: <strong><?php echo $this->getItem()->getQtyOrdered()*1 ?></strong><br />
        <?php endif; ?>
        <?php if ($this->getItem()->getQtyShipped() > 0): ?>
            <?php echo $this->__('Shipped'); ?>: <strong><?php echo $this->getItem()->getQtyShipped()*1 ?></strong><br />
        <?php endif; ?>
        <?php if ($this->getItem()->getQtyCanceled() > 0): ?>
            <?php echo $this->__('Canceled'); ?>: <strong><?php echo $this->getItem()->getQtyCanceled()*1 ?></strong><br />
        <?php endif; ?>
        <?php if ($this->getItem()->getQtyRefunded() > 0): ?>
            <?php echo $this->__('Refunded'); ?>: <strong><?php echo $this->getItem()->getQtyRefunded()*1 ?></strong><br />
        <?php endif; ?>
        </span>
    </td>
    <td>
    </td>
</tr>