<div class="box-collateral box-reviews box-views" id="customer-reviews">
	<?php if ($this->isDisplayReview()):?>
		<?php echo $this->getChildHtml('review_form');?>
	<?php else:?>
		<?php echo $this->getReviewNotice();?> <br/>
	<?php endif;?>
	
	<?php $_items = $this->getReviewsCollection()->getItems();?>
	<?php if (count($_items)):?>
	<?php echo $this->getChildHtml('toolbar') ?>
	<ul class="reviewslsist">
		<?php foreach ($_items as $_review):?>
		<li class="clearfix">
			<div class="titles clearfix"> <?php echo $this->__('<span> 评论：%s</span>', $this->htmlEscape($_review->getNickname())) ?><strong>标题：<?php echo $this->htmlEscape($_review->getTitle()) ?></strong><small class="date"><?php echo $this->__('(Posted on %s)', $this->formatDate($_review->getCreatedAt()), 'long') ?></small></div>
			<?php $_votes = $_review->getRatingVotes(); ?>
			<?php if (count($_votes)): ?>
			<div class="ratings-table">
				<?php foreach ($_votes as $_vote): ?>
				<div class="ratings clearfix"><span class="bfL name"><?php echo $this->escapeHtml($_vote->getRatingCode()) ?>：</span>
					<div class="rating-box">
						<div class="rating" style="width:<?php echo $_vote->getPercent() ?>%;"></div>
					</div>
				</div>
				<?php endforeach; ?>
			</div>
			<?php endif; ?>
			<div class="conts">
				<p><?php echo nl2br($this->htmlEscape($_review->getDetail())) ?></p>
				<p class="reply"><?php echo nl2br($this->htmlEscape($_review->getReplyContent())) ?></p>
			</div>
		</li>
		<?php endforeach; ?>
	</ul>
	<?php echo $this->getChildHtml('toolbar') ?>
	<?php endif;?>
</div>
