<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="fieldset clearfix">
<h2 class="legend"><?php echo $this->__('My Product Reviews') ?></h2>
<?php if( $this->getCollection() && $this->count()): ?>
        <table class="data-table" id="my-reviews-table">
            <tbody>
                <?php foreach ($this->getCollection() as $_review): ?>
                <tr>
                    <td><?php echo $this->dateFormat($_review->getCreatedAt()) ?></td>
                    <td><h2 class="product-name"><a href="<?php echo $this->getProductLink() ?>id/<?php echo $_review->getEntityPkValue() ?>"><?php echo $this->htmlEscape($_review->getName()) ?></a></h2></td>
                    <td>
                    <?php if($_review->getSum()): ?>
                        <div class="rating-box">
                            <div class="rating" style="width:<?php echo ( $_review->getSum() / $_review->getCount() ) ?>%;"></div>
                        </div>
                    <?php endif; ?>
                    </td>
                    <td><?php echo $this->htmlEscape($this->helper('review')->getDetail($_review->getDetail())) ?></td>
                    <td><a href="<?php echo $this->getReviewLink() ?>id/<?php echo $_review->getReviewId() ?>" class="nobr"><?php echo $this->__('View') ?></a></td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
        <script type="text/javascript">decorateTable('my-reviews-table')</script>
    <?php echo $this->getToolbarHtml() ?>
<?php else: ?>
    <p><?php echo $this->__('You have submitted no reviews.') ?></p>
<?php endif; ?>
</div>
