<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

<form action="<?php echo $this->getSearchPostUrl() ?>" method="get" id="form-validate">
	<div class="fieldset advanced-search">
		<h2 class="legend"><?php echo $this->__('Catalog Advanced Search') ?></h2>
		<ul class="form_list" id="advanced-search-list">
			<?php foreach ($this->getSearchableAttributes() as $_attribute): ?>
			<?php $_code = $_attribute->getAttributeCode() ?>
			<li class="fields">
				<label for="<?php echo $_code ?>" class="label-like"><?php echo $this->getAttributeLabel($_attribute) ?></label>
				<?php switch($this->getAttributeInputType($_attribute)):
                    case 'number': ?>
				<div class="input-range">
					<input type="text" name="<?php echo $_code ?>[from]" value="<?php echo $this->htmlEscape($this->getAttributeValue($_attribute, 'from')) ?>" id="<?php echo $_code ?>" title="<?php echo $this->htmlEscape($this->getAttributeLabel($_attribute)) ?>" class="input-text validate-number" />
					<span class="separator">-</span>
					<input type="text" name="<?php echo $_code ?>[to]" value="<?php echo $this->htmlEscape($this->getAttributeValue($_attribute, 'to')) ?>" id="<?php echo $_code ?>_to" title="<?php echo $this->htmlEscape($this->getAttributeLabel($_attribute)) ?>" class="input-text validate-number" />
				</div>
				<?php break;
                    case 'price': ?>
				<div class="input-range">
					<input name="<?php echo $_code ?>[from]" value="<?php echo $this->htmlEscape($this->getAttributeValue($_attribute, 'from')) ?>" id="<?php echo $_code ?>" title="<?php echo $this->htmlEscape($this->getAttributeLabel($_attribute)) ?>"  class="input-text validate-number" type="text" />
					<span class="separator">-</span>
					<input name="<?php echo $_code ?>[to]" value="<?php echo $this->htmlEscape($this->getAttributeValue($_attribute, 'to')) ?>" id="<?php echo $_code ?>_to" title="<?php echo $this->htmlEscape($this->getAttributeLabel($_attribute)) ?>"  class="input-text validate-number" type="text" />
					<small>(<?php echo $this->getCurrency($_attribute); ?>)</small> </div>
				<?php break;
                    case 'select': ?>
				<div class="input-box"> <?php echo $this->getAttributeSelectElement($_attribute) ?> </div>
				<?php break;
                    case 'yesno': ?>
				<?php echo $this->getAttributeYesNoElement($_attribute) ?>
				<?php break;
                    case 'date': ?>
				<div class="input-range"> <?php echo $this->getDateInput($_attribute, 'from') ?> <span class="separator">-</span> <?php echo $this->getDateInput($_attribute, 'to') ?> </div>
				<?php break;
                    default: ?>
				<div class="input-box">
					<input type="text" name="<?php echo $_code ?>" id="<?php echo $_code ?>" value="<?php echo $this->htmlEscape($this->getAttributeValue($_attribute)) ?>" title="<?php echo $this->htmlEscape($this->getAttributeLabel($_attribute)) ?>"  class="input-text <?php echo $this->getAttributeValidationClass($_attribute) ?>" />
				</div>
				<?php endswitch; ?>
			</li>
			<?php endforeach; ?>
			<li class="fields">
				<button type="submit" title="<?php echo $this->__('Search') ?>" class="button"><span><span><?php echo $this->__('Search') ?></span></span></button>
			</li>
		</ul>
		<script type="text/javascript">decorateList('advanced-search-list')</script> 
	</div>
</form>
<script type="text/javascript">
//<![CDATA[
$(function() {
	$('#form-validate').makingwareFormValidator();
});
//]]>
</script>