<?php  $_order = $this->getOrder() ?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="order_title  clearfix">
	<div class="boeder">
		<h2>
		<?php if($this->helper('rss/order')->isStatusNotificationAllow()): ?>
<a href="<?php echo $this->helper('rss/order')->getStatusHistoryRssUrl($_order) ?>" class="link-rss"><?php echo $this->__('Subscribe to Order Status') ?></a> <span class="separator">|</span>
			<?php endif; ?>

			<?php echo $this->__('Order #: %s', $_order->getRealOrderId()) ?> &nbsp;&nbsp; <?php echo $this->__('Status');?>: <em><?php echo $this->__('%s', $_order->getStatusLabel()) ?></em></h2>
		<span class="order-date"><?php echo $this->__('Order Date: %s', $this->formatDate($_order->getCreatedAtStoreDate(), 'long')) ?></span> </div>
</div>
<?php echo $this->getStatusHistoryRssUrl($_order) ?>
<div class="oreder_info">
	<dl class="order-info">
		<dt><?php echo $this->__('About This Order:') ?></dt>
		<dd>
		<ul id="order-info-tabs">
		<li class="current"><?php echo $this->__('Order Information');?></li></ul>
			<?php /*?><?php $_links = $this->getLinks(); ?>
			<ul id="order-info-tabs">
				<?php foreach ($_links as $_link): ?>
				<?php if($_link->getUrl()): ?>
				<li><a href="<?php echo $_link->getUrl() ?>"><?php echo $_link->getLabel() ?></a></li>
				<?php else: ?>
				<li class="current"><?php echo $_link->getLabel() ?></li>
				<?php endif; ?>
				<?php endforeach; ?>
			</ul><?php */?>
		</dd>
	</dl>
	<div class="order-items clearfix">
		<?php if (!$_order->getIsVirtual()): ?>
		<div class="order_row">
			<h6><?php echo $this->__('Shipping Address') ?></h6>
			<address>
			<?php echo $_order->getShippingAddress()->format('html') ?>
			</address>
		</div>
		<div class="order_row">
			<h6><?php echo $this->__('Payment and Shipping Method') ?>
				<?php /* | <a href="#"><?php echo $this->__('Track Order') ?></a>*/ ?>
			</h6>
			<?php if ($_order->getShippingDescription()): ?>
			<?php echo $_order->getShippingDescription() ?>
			<?php else: ?>
			<p><?php echo $this->helper('sales')->__('No shipping information available'); ?></p>
			<?php endif; ?>
			<?php echo $this->getPaymentInfoHtml() ?> </div>
		<?php $billInfo= $this->getBillInfo();?>
		<?php if($billInfo->getId()): ?>
		<div class="order_row">
			<h6><?php echo $this->__('Invoice Information');?></h6>
           <?php if($billInfo->getId()): ?>
			<ul>
				<li><?php echo $this->__('Invoice Type');?>：
					<?php $type=$billInfo->getType();?><?php if($type==0){echo $this->__('General Invoice');}else{echo $this->__('VAT Invoice');}?>
				</li>
				<li><?php echo $this->__('Invoices Payable');?>：
					<?php $title=$billInfo->getTitle();?><?php if($title==0){echo $this->__('Personal');}else{echo $this->__('Units');}?>
				</li>
				<?php $company=$billInfo->getCompany();?>
				<?php if($company): ?>
				<li><?php echo $this->__('Units Name');?>：
				<?php echo $company; ?>
				</li>
				<?php endif;?>
				<li><?php echo $this->__('Invoice Content');?>：
					<?php $content=$billInfo->getContent();?>
					<?php if($content==0): ?><?php echo $this->__('Detail');?>
					<?php elseif($content==1): ?><?php echo $this->__('Office Supplies');?>
					<?php elseif($content==2): ?><?php echo $this->__('Computer Accessories');?>
					<?php elseif($content==3): ?><?php echo $this->__('Consumable');?>
					<?php endif;?>
				</li>
			</ul>
		</div>
		<?php endif; ?>
		<?php endif; ?>
		<?php endif; ?>
		<?php echo $this->getChildHtml('searchorder_items') ?> </div>
</div>