<?php $_product = $this->getProduct() ?>

<div class="price-box">
    <p class="price-as-configured">
        <span class="price-label"><?php echo $this->helper('bundle')->__('价格') ?>:</span>
        <span class="price" id="product-price-<?php echo $_product->getId() ?><?php echo $this->getIdSuffix() ?>"></span>
    </p>
</div>
<?php if($_product->isSaleable()): ?>
<script type="text/javascript">
bundle.reloadPrice();
</script>
<?php endif; ?>
