<div class="col-main">
    <div class="page-title">
        <h1>有一个错误请求</h1>
    </div>
    <?php if ($this->showSentMsg): ?>
    <ul class="messages">
        <li class="success-msg">
            <ul>
                <li>您的留言已提交，并会尽快作出回应。感谢您的报告。</li>
            </ul>
        </li>
    </ul>
    <?php endif; ?>
    <?php if ($this->showSendForm): ?>
    <ul class="messages">
        <li class="note-msg">
            <ul>
                <li>我们目前遇到的一些技术问题。给您带来的不便，我们深表歉意，并会尽快与您联系以解决问题。为了帮助我们为您更好的服务，请填写下面的表格。</li>
            </ul>
        </li>
    </ul>
        <?php if ($this->showErrorMsg): ?>
    <ul class="messages">
        <li class="error-msg">
            <ul>
                <li>请认真填写所有信息</li>
            </ul>
        </li>
    </ul>
        <?php endif; ?>
    <form action="<?php echo "{$this->getBaseUrl(true)}errors/report.php?id={$this->reportId}" ?>" method="post" id="form-validate">
        <fieldset class="fieldset">
            <h2>Personal Information</h2>
            <ul class="form-list group-select">
                <li class="fields">
                    <div class="field">
                        <label for="firstname" class="required"><em>*</em>姓</label>
                        <span class="input-box"><input type="text" name="firstname" id="firstname" value="<?php echo $this->postData['firstName'] ?>" title="First Name" class="required-entry input-text" /></span>
                    </div>
                    <div class="field">
                        <label for="lastname" class="required"><em>*</em>名</label>
                        <span class="input-box"><input type="text" name="lastname" id="lastname" value="<?php echo $this->postData['lastName'] ?>" title="Last Name" class="required-entry input-text" /></span>
                    </div>
                </li>
                <li class="fields">
                    <div class="field">
                        <label for="firstname" class="required"><em>*</em>邮箱地址</label>
                        <span class="input-box"><input type="text" name="email" id="email_address" value="<?php echo $this->postData['email'] ?>" title="Email Address" class="validate-email required-entry input-text" /></span>
                    </div>
                    <div class="field">
                        <label for="firstname">联系电话</label>
                        <span class="input-box"><input type="text" name="telephone" id="telephone" value="<?php echo $this->postData['telephone'] ?>" title="Telephone" class="input-text" /></span>
                    </div>
                </li>
                <li>
                    <div class="input-box">
                        <label for="firstname">内容</label>
                        <span class="input-box"><textarea name="comment" cols="5" rows="3"><?php echo $this->postData['comment'] ?></textarea></span>
                    </div>
                </li>
            </ul>
        </fieldset>
        <div class="buttons-set form-buttons btn-only">
            <button name="submit" class="button" type="submit"><span><span>提交</span></span></button>
        </div>
        <p class="required">* 必填</p>
    </form>
    <?php elseif ('' == $this->reportAction): ?>
        <p><em>出于安全原因默认情况下禁用打印。</em></p>
    <?php endif; ?>

    <?php if ($this->reportAction == 'print'): ?>
    <div class="trace-container">
        <div class="trace">
            <pre><?php echo $this->reportData[0] ?><br />
<strong>Trace:</strong>
<?php echo htmlspecialchars($this->reportData[1]) ?><br />
</pre>
        </div>
    </div>
    <?php endif; ?>
    <?php if ($this->reportId && $this->reportUrl): ?>
        <p>Error log record number: <a href="<?php echo htmlspecialchars($this->reportUrl) ?>"><?php echo $this->reportId ?></a></p>
    <?php endif; ?>
</div>
